version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node --version
      - npm install

  build:
    commands:
      - npx nx build Document-Library-Search-System --verbose
      # - echo "Invalidating CloudFront distribution $DISTRIBUTION_ID..."
      # - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist/apps/Document-Library-Search-System
